name: Node.js CI/CD

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.9'
      - run: npm ci
      - run: npm run build --if-present
      # - run: npm test
      - name: Configure AWS credentials from Test Account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Copy files to the test website with the AWS CLI
        run: |
        aws s3 sync build/ s3://20250512-fm-react-handson --delete